### ISSUE TITLE
Releases broken due to false line endings in the TDL.INI and HANDLERS.INI files?

### ISSUE THREAD

**Issue by theMK2k** [MobyGamer/total-dos-launcher#38]
I've been experimenting with the official TDL binary releases (TDLIndexer.py and /distro directory) and it seems that the .zip releases of TDL 0.1.0 - 0.1.2 provide the /distro/TDL.INI and /distro/HANDERS.INI with wrong line endings:
- provided: Lf (0x0a)
- apparently expected by TDL.EXE: CrLf (0x0d 0x0a)

With the provided .INI files you get error messages when running TDL.EXE.

**Comment by MobyGamer** [comment]
You're right, it looks like the line endings were translated as part of doing the git push.  I'll see how I can fix that on my end for just the .INI files.

**Comment by MobyGamer** [comment]
Looks like https://help.github.com/articles/dealing-with-line-endings/ will definitely fix this.

**Comment by MobyGamer** [comment]
Fixed.

**Comment by theMK2k** [comment]
Thanks for the last fixes/enhancements.

As you may have guessed, I'm still not able to set up the TP dev environment to successfully build TDL. Could you provide a new binary release? Thanks :)

**Comment by MobyGamer** [comment]
Sorry about that; pushed release 0.1.3.  You can also just grab new .INI files and the .EXE file from the distro/ subdir if you want.
